CREATE TABLE ITEM(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(8000) NOT NULL,
  BUILD_YEAR BIGINT NOT NULL,
  PRICE BIGINT NOT NULL,
  IS_AVAILABLE BIT NOT NULL,
  IMAGE_URL VARCHAR(260) NOT NULL
);
